## sign up with form

POST http://localhost:3000/auth/local/signup
Content-Type: application/json

{
  "firstName":"mai",
  "lastName":"Mohamed",
  "email":"esrafa@gmail.com",
  "phoneNumber":"01270304453",
  "password":"Esraaguest5056@"
}


### login user with form
POST http://localhost:3000/auth/local/login
Content-Type: application/json

{
  "email":"esraa@gmail.com",
  "password":"Esraaguest5056@"
}

### logout user

Post http://localhost:3000/auth/logout


### refresh accessToken